plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - "chapter_1/main.md"
  
theme: jekyll-theme-modernist

markdown: kramdown


title: "Research Data Management Book of Knowledge"
