plugins:
  - jekyll-relative-links
  - jekyll-titles-from-headings
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - chapter_1.md

  
markdown: kramdown


title: "Research Data Management Book of Knowledge"

theme: jekyll-theme-slate