plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - chapter_1.md

  
theme: jekyll-titles-from-headings

markdown: kramdown


title: "Research Data Management Book of Knowledge"
