plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - chapter_*/*.md
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md

theme: jekyll-theme-modernist

markdown: kramdown


title: "Research Data Management Book of Knowledge"
