plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - chapter_1/main.md
  - README.md

theme: jekyll-theme-modernist

markdown: kramdown


title: "Research Data Management Book of Knowledge"
