plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
- chapter_1.md



  
markdown: kramdown


title: "Research Data Management Book of Knowledge"

theme: jekyll-theme-slate
